import { hubReturnButton } from './hubReturnButton.js';
import {BOARD_CONTENTS,BOARD_CATEGORIES,BOARD_STATUSES} from '../platform/hubBoardCatalog.js';
import { hubNoticeImageUrl } from '../lib/hubBoardApi.js';
import { noticeBodySegments, markerForNoticeImage } from '../lib/hubNoticeMedia.js';
const e=value=>String(value??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#39;');
const date=value=>value?new Date(value).toLocaleDateString('ko-KR'):'-';
const label=(map,key)=>map[key]||'기타';
const icon=(name,size=20)=>{const shapes={
 notice:'<path d="M3 10v4h4l8 4V6L7 10H3z"/><path d="M7 14l1 5h3l-1.6-4.2M18 8a5 5 0 0 1 0 8"/>',
 headset:'<path d="M3 13v-2a9 9 0 0 1 18 0v2M3 13h4v7H6a3 3 0 0 1-3-3v-4zm18 0h-4v7h1a3 3 0 0 0 3-3v-4z"/><path d="M18 20a6 6 0 0 1-6 3h-2"/>',
 chat:'<path d="M20 12a8 8 0 0 1-8 8 9 9 0 0 1-4-.9L3 21l1.7-4A8 8 0 1 1 20 12Z"/><circle cx="8" cy="12" r=".7" fill="currentColor" stroke="none"/><circle cx="12" cy="12" r=".7" fill="currentColor" stroke="none"/><circle cx="16" cy="12" r=".7" fill="currentColor" stroke="none"/>',
 bulb:'<path d="M9 18h6M9 21h6M9 18c0-2-4-4-4-8a7 7 0 1 1 14 0c0 4-4 6-4 8M12 1v2M2 10h2M20 10h2M4.5 3.5l1.5 1.5M19.5 3.5 18 5"/>',
 bug:'<path d="M8 6 6 3M16 6l2-3M7 10H3m4 4H3m4 4-3 3m13-11h4m-4 4h4m-4 4 3 3M9 6h6l3 4v5a6 6 0 0 1-12 0v-5zM12 6v13"/>',
 question:'<circle cx="12" cy="12" r="9"/><path d="M9.4 9a3 3 0 1 1 5 2.3c-1.4 1-2.4 1.4-2.4 3.2M12 18h.01"/>',
 warning:'<path d="m12 3 10 18H2L12 3zM12 9v5M12 18h.01"/>',
 sparkle:'<path d="m12 2 2.8 7.2L22 12l-7.2 2.8L12 22l-2.8-7.2L2 12l7.2-2.8L12 2z"/>',
 search:'<circle cx="10.8" cy="10.8" r="7"/><path d="m16 16 5 5"/>',
 check:'<circle cx="12" cy="12" r="9"/><path d="m7.5 12 3 3 6-6"/>',
 clock:'<circle cx="12" cy="12" r="9"/><path d="M12 7v6l4 2"/>',
 document:'<path d="M5 2h10l4 4v16H5zM15 2v5h4M8 11h8M8 15h8M8 19h5"/>',
 pencil:'<path d="M4 20l4.5-1 12-12a2 2 0 0 0-3-3l-12 12L4 20ZM15 6l3 3"/>',
 arrow:'<path d="M4 12h16m-7-7 7 7-7 7"/>',
 image:'<rect x="3" y="3" width="18" height="18" rx="2"/><circle cx="8" cy="8" r="1"/><path d="m3 17 5-5 4 4 4-5 5 5"/>',
 };return `<svg class="hub-ui-icon hub-ui-icon--${name}" xmlns="http://www.w3.org/2000/svg" width="${size}" height="${size}" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${shapes[name]||shapes.sparkle}</svg>`;};
const fileCards=(files=[],messageId=null)=>files.filter(item=>(item.message_id||null)===(messageId||null)).map((item,index)=>`<button type="button" class="hub-board__image" data-action="hub-board-image" data-image-path="${e(item.storage_path)}" aria-label="첨부 사진 ${index+1} 크게 보기" title="사진 크게 보기">${item.signedUrl?`<img src="${e(item.signedUrl)}" alt="첨부 사진 ${index+1}" loading="lazy">`:`<span aria-hidden="true">▧</span>`}</button>`).join('');
const pendingFiles=state=>(state.hubBoard?.files||[]).map(item=>`<div class="hub-board__preview"><img src="${e(item.url)}" alt="첨부 예정 사진"><button type="button" data-action="hub-board-file-remove" data-file-id="${e(item.id)}" aria-label="첨부 제거">×</button></div>`).join('');
const attach=state=>`<label class="hub-board__attach" data-hub-board-drop>＋ 사진 첨부 <input type="file" accept="image/jpeg,image/png,image/webp" multiple data-hub-board-images></label><span class="hub-board__help">JPG · PNG · WEBP / 한 장 10MB 이하 / 최대 5장 · 붙여넣기도 가능</span><div class="hub-board__previews" aria-live="polite">${pendingFiles(state)}</div>`;
const noticeMediaPreviews=state=>(state.hubBoard?.noticeMedia||[]).filter(item=>!item.removed).map(item=>`<div class="hub-board__notice-preview"><img src="${e(item.url)}" alt="공지 이미지 미리보기"><div><strong>${e(markerForNoticeImage(item.key))}</strong><small>본문의 이 표기 위치에 이미지가 표시됩니다.</small></div><button type="button" data-action="hub-board-notice-image-remove" data-notice-image-key="${e(item.key)}">제거</button></div>`).join('');
const noticeAttach=state=>`<div class="hub-board__notice-image-tools"><label class="hub-board__attach">＋ 이미지 추가 <input type="file" accept="image/jpeg,image/png,image/webp" multiple data-hub-notice-images></label><span class="hub-board__help">원하는 위치에 커서를 둔 뒤 이미지를 Ctrl+V로 붙여넣을 수 있습니다. · JPG/PNG/WEBP · 한 장 10MB 이하 · 최대 8장</span><div class="hub-board__notice-previews" aria-live="polite">${noticeMediaPreviews(state)}</div></div>`;
const noticeBodyHtml=body=>noticeBodySegments(body).map((segment,index)=>segment.type==='image'?`<figure class="hub-board__notice-image"><img src="${e(hubNoticeImageUrl(segment.path))}" alt="공지 이미지 ${index+1}" loading="lazy" decoding="async"></figure>`:`<div class="hub-board__notice-copy">${e(segment.value)}</div>`).join('');
const formActions=(name='등록하기')=>`<div class="hub-board__form-actions"><button type="button" class="hub-board__ghost" data-action="hub-board-cancel">취소</button><button type="submit" class="hub-board__primary">${name} →</button></div>`;
export function renderHubNewsStrip(state){
 const notices=(state.hubBoard?.notices||[]).slice(0,3);
 const noticeEntries=notices.map((item,index)=>`<button type="button" class="hub-news__item" data-action="hub-board-notice" data-notice-id="${e(item.id)}"><span class="hub-news__item-tag">${index===0?'최신':'공지'}</span><span class="hub-news__item-title">${e(item.title)}</span><small>${date(item.published_at)}</small><span class="hub-news__item-arrow" aria-hidden="true">↗</span></button>`).join('');
 return `<section class="hub-news" aria-label="LAC HUB 사이트 공지와 문의"><div class="hub-news__notice"><div class="hub-news__header"><span class="hub-news__icon" aria-hidden="true">${icon('notice',21)}</span><div><span class="hub-news__eyebrow">사이트 공지</span></div><button type="button" data-action="hub-board-notices" class="hub-news__more">전체 공지 <span aria-hidden="true">↗</span></button></div><div class="hub-news__items">${noticeEntries||`<div class="hub-news__empty"><strong>아직 등록된 공지가 없습니다.</strong><span>${state.hubBoard?.error?'게시판 연결 상태를 확인해 주세요.':'새 공지가 등록되면 이곳에 표시됩니다.'}</span></div>`}</div><p class="hub-news__notice-foot">게임 내 공식 공지와 별개인 LAC HUB 사이트 안내입니다.</p></div><div class="hub-news__support"><div class="hub-news__header"><span class="hub-news__icon" aria-hidden="true">${icon('headset',21)}</span><div><span class="hub-news__eyebrow">문의 · 건의</span></div></div><div class="hub-news__support-types"><span><b class="hub-news__type-icon is-chat" aria-hidden="true">${icon('chat',19)}</b><span><strong>서비스 문의</strong></span></span><span><b class="hub-news__type-icon is-bulb" aria-hidden="true">${icon('bulb',19)}</b><span><strong>개선 제안</strong></span></span><span><b class="hub-news__type-icon is-bug" aria-hidden="true">${icon('bug',19)}</b><span><strong>오류 신고</strong></span></span></div><div class="hub-news__actions"><button type="button" data-action="hub-board-open" class="hub-news__all">게시판 가기 <span aria-hidden="true">↗</span></button><button type="button" data-action="hub-board-compose" class="hub-news__write">문의 · 건의 작성 <span aria-hidden="true">→</span></button></div></div></section>`;
}
export function renderHubBoard(state){
 const board=state.hubBoard||{};const mode=board.mode||'list';const tab=board.tab||'support';
 const isAdmin=state.platformAdmin===true;
 const top=`<div class="hub-board__top"><div class="hub-board__return">${hubReturnButton('hub-board__back')}</div><div class="hub-board__brand"><img src="/hub/mark.png" width="29" height="29" alt=""><strong>LAC HUB</strong><span>SUPPORT</span></div><div class="hub-board__topnav"><span>고객지원</span></div></div>`;
 const heading=`<header class="hub-board__heading ${mode==='list'?'':'hub-board__heading--compact'}"><div class="hub-board__hero-shade"></div><div class="hub-board__hero-copy"><span>LAC HUB SUPPORT</span><h1>공지 · 문의 · 건의</h1><p>게임 정보와 LAC HUB 서비스에 관한 질문과 의견을 남길 수 있는 공간입니다.</p></div></header>`;
 const message=board.error?`<div class="hub-board__error" role="alert">${e(board.error)}<small>최초 적용 시에는 데이터베이스에 Phase 19 게시판 SQL을 먼저 실행해야 합니다. 기존 회사 관리 게시판과 데이터는 그대로 보존됩니다.</small></div>`:'';
 const notices=(board.notices||[]);
 const ticketRows=(board.tickets||[]).filter(item=>
  (board.filterContent==='all'||!board.filterContent||item.content_key===board.filterContent)&&
  (board.filterCategory==='all'||!board.filterCategory||item.category===board.filterCategory)&&
  (board.filterStatus==='all'||!board.filterStatus||item.status===board.filterStatus)&&
  (!board.searchQuery||`${item.title||''} ${item.author_name||''} ${label(BOARD_CONTENTS,item.content_key)} ${label(BOARD_CATEGORIES,item.category)}`.toLocaleLowerCase().includes(String(board.searchQuery).trim().toLocaleLowerCase()))
 );
 const tabs=`<nav class="hub-board__tabs" aria-label="게시판 구분"><button type="button" data-action="hub-board-tab" data-board-tab="support" class="${tab==='support'?'is-active':''}" ${tab==='support'?'aria-current="page"':''}><span class="hub-board__tab-icon" aria-hidden="true">${icon('headset',20)}</span><span><strong>문의 · 건의</strong><small>내 글과 답변을 확인하세요.</small></span></button><button type="button" data-action="hub-board-tab" data-board-tab="notices" class="${tab==='notices'?'is-active':''}" ${tab==='notices'?'aria-current="page"':''}><span class="hub-board__tab-icon" aria-hidden="true">${icon('notice',20)}</span><span><strong>공지사항</strong><small>운영자가 등록한 공식 안내입니다.</small></span></button></nav>`;
 const noticeList=`<section class="hub-board__list hub-board__list--notices"><div class="hub-board__list-head"><div><span class="hub-board__section-kicker">OFFICIAL NOTICE</span><strong>공지사항</strong><small>플랫폼 운영자가 등록한 공식 안내입니다.</small></div>${isAdmin?`<button type="button" class="hub-board__ghost" data-action="hub-board-notice-compose">${icon('pencil',15)} 공지 작성</button>`:''}</div>${notices.length?notices.map(item=>`<button type="button" class="hub-board__row hub-board__row--notice" data-action="hub-board-notice" data-notice-id="${e(item.id)}"><span class="hub-board__pill hub-board__pill--notice">공지</span><span class="hub-board__row-copy"><strong>${e(item.title)}</strong></span><small>${date(item.published_at)}</small><span class="hub-board__row-enter" aria-hidden="true">→</span></button>`).join(''):`<div class="hub-board__empty hub-board__empty--rich"><span aria-hidden="true">${icon('notice',22)}</span><strong>등록된 공지가 없습니다.</strong><p>새로운 공식 안내는 등록되는 대로 이곳에 표시됩니다.</p></div>`}</section>`;
 const filters=`<div class="hub-board__filters"><label>콘텐츠 <select data-hub-board-filter="content"><option value="all">전체</option>${Object.entries(BOARD_CONTENTS).map(([key,value])=>`<option value="${key}" ${board.filterContent===key?'selected':''}>${value}</option>`).join('')}</select></label><label>문의 유형 <select data-hub-board-filter="category"><option value="all">전체</option>${Object.entries(BOARD_CATEGORIES).map(([key,value])=>`<option value="${key}" ${board.filterCategory===key?'selected':''}>${value}</option>`).join('')}</select></label><label>답변 상태 <select data-hub-board-filter="status"><option value="all">전체</option>${Object.entries(BOARD_STATUSES).map(([key,value])=>`<option value="${key}" ${board.filterStatus===key?'selected':''}>${value}</option>`).join('')}</select></label></div>`;
 const tickets=`<section class="hub-board__list hub-board__list--tickets"><div class="hub-board__list-head"><div><span class="hub-board__section-kicker">PRIVATE SUPPORT</span><strong>${isAdmin?'전체 문의 · 건의':'내 문의 · 건의'} <em>${ticketRows.length}건 표시 중</em></strong><small>작성자와 LAC HUB 운영자만 글과 첨부 사진을 볼 수 있습니다.</small></div><label class="hub-board__search">${icon('search',15)} <input type="search" data-hub-board-search value="${e(board.searchQuery||'')}" placeholder="제목 · 작성자 검색" aria-label="문의 검색"></label></div><div class="hub-board__filterbar">${filters}</div>${ticketRows.length?`<div class="hub-board__tablehead"><span>상태</span><span>제목</span><span>콘텐츠</span><span>작성자</span><span>작성일</span><span></span></div>${ticketRows.map(item=>`<button type="button" class="hub-board__row hub-board__row--ticket" data-action="hub-board-ticket" data-ticket-id="${e(item.id)}"><span class="hub-board__status hub-board__status--${e(item.status)}">${e(label(BOARD_STATUSES,item.status))}</span><span class="hub-board__row-copy"><strong>${e(item.title)}</strong><small>${e(label(BOARD_CATEGORIES,item.category))}</small></span><span class="hub-board__pill">${e(label(BOARD_CONTENTS,item.content_key))}</span><small class="hub-board__author">${isAdmin?e(item.author_name||'작성자'):'나'}</small><small>${date(item.updated_at)}</small><span class="hub-board__row-enter" aria-hidden="true">→</span></button>`).join('')}`:`<div class="hub-board__empty hub-board__empty--rich"><span aria-hidden="true">${icon('chat',22)}</span><strong>${board.searchQuery||board.filterCategory&&board.filterCategory!=='all'||board.filterContent&&board.filterContent!=='all'||board.filterStatus&&board.filterStatus!=='all'?'검색 조건에 맞는 문의가 없습니다.':'아직 등록된 문의가 없습니다.'}</strong><p>궁금한 점이나 개선 의견이 있다면 문의를 남겨주세요.<br>내용과 사진은 작성자 본인과 LAC HUB 운영자만 확인할 수 있습니다.</p><button type="button" class="hub-board__primary" data-action="hub-board-compose">${icon('pencil',15)} 문의 · 건의 작성</button></div>`}</section>`;
 const statusCounts={pending:0,checking:0,complete:0};
 for(const item of (board.tickets||[]))if(Object.hasOwn(statusCounts,item.status))statusCounts[item.status]++;
 const supportProgress=`<div class="hub-board__progress" aria-label="조회 가능한 문의 상태"><span><b>${statusCounts.pending}</b><small>답변 대기</small></span><span><b>${statusCounts.checking}</b><small>확인 중</small></span><span><b>${statusCounts.complete}</b><small>처리 완료</small></span></div>`;
 const recentItems=(board.tickets||[]).filter(item=>item.status==='complete').slice(0,2);
 const recentReplies=`<section class="hub-board__recent"><span class="hub-board__recent-icon">${icon('check',19)}</span><div><strong>최근 처리된 문의</strong><small>${recentItems.length?'조회 가능한 완료 글':'처리 완료된 문의가 등록되면 이곳에 표시됩니다.'}</small></div>${recentItems.map(item=>`<button type="button" data-action="hub-board-ticket" data-ticket-id="${e(item.id)}"><span class="hub-board__status hub-board__status--complete">처리 완료</span><span>${e(item.title)}</span>${icon('arrow',14)}</button>`).join('')}</section>`;
 const noticeInfo=`<section class="hub-board__notice-info"><span class="hub-board__section-kicker">LAC HUB · OFFICIAL</span><strong>운영 공지를 확인해 주세요.</strong><p>서비스 이용과 변경 사항은 운영자가 등록한 공식 공지로 안내합니다. 문의나 개선 의견은 별도 문의 · 건의 탭에서 남길 수 있습니다.</p><div><span>공개 안내</span><span>문의 · 건의는 비공개</span></div></section>`;
 const supportSide=`<aside class="hub-board__side"><div class="hub-board__side-card"><span class="hub-board__section-kicker">HOW CAN WE HELP?</span><h2>빠른 문의</h2><p>문의 유형별로 내가 작성한 글을 확인하세요.</p><div class="hub-board__quicklist"><button type="button" data-action="hub-board-quick" data-board-category="question" class="${board.filterCategory==='question'?'is-active':''}"><span class="hub-board__quick-icon is-chat" aria-hidden="true">${icon('question',19)}</span><span><b>질문</b><small>이용 방법과 기능 문의</small></span><span aria-hidden="true">↗</span></button><button type="button" data-action="hub-board-quick" data-board-category="bug" class="${board.filterCategory==='bug'?'is-active':''}"><span class="hub-board__quick-icon is-bug" aria-hidden="true">${icon('bug',19)}</span><span><b>오류 신고</b><small>비정상 동작 및 문제 제보</small></span><span aria-hidden="true">↗</span></button><button type="button" data-action="hub-board-quick" data-board-category="suggestion" class="${board.filterCategory==='suggestion'?'is-active':''}"><span class="hub-board__quick-icon is-bulb" aria-hidden="true">${icon('bulb',19)}</span><span><b>건의</b><small>서비스 개선 의견</small></span><span aria-hidden="true">↗</span></button></div></div><div class="hub-board__side-card hub-board__side-card--guide"><span class="hub-board__section-kicker">BEFORE YOU WRITE</span><h3>문의 전 확인해 주세요</h3><p>✓ 관련 콘텐츠와 문의 유형을 선택해 주세요.</p><p>✓ 문제 상황과 확인한 내용을 알려주세요.</p><p>✓ 화면 캡처를 첨부하면 상황 파악에 도움이 됩니다.</p><div class="hub-board__private-note">▣ 문의와 사진은 작성자 및 운영자에게만 공개됩니다.</div></div></aside>`;
 const noticesSide=`<aside class="hub-board__side"><div class="hub-board__side-card hub-board__side-card--notice"><span class="hub-board__section-kicker">LAC HUB NEWS</span><h2>공지사항</h2><p>서비스 이용 안내와 운영 소식을 확인하는 공간입니다.</p><div class="hub-board__side-art" aria-hidden="true"></div><div class="hub-board__private-note">✦ 이 영역에는 LAC HUB 전체 공지만 표시됩니다.</div></div><div class="hub-board__side-card hub-board__side-card--guide"><h3>궁금한 점이 있나요?</h3><p>서비스 이용 문의나 개선 의견은 별도의 문의 · 건의 게시판에 남길 수 있습니다.</p><button type="button" class="hub-board__ghost" data-action="hub-board-tab" data-board-tab="support">문의 · 건의 보기 →</button></div></aside>`;
 let contents='';
 if(mode==='compose'){
  contents=`<section class="hub-board__sheet"><div class="hub-board__sheet-top"><span>새 글 작성</span><button type="button" data-action="hub-board-cancel">×</button></div><form data-form="hub-board-ticket" class="hub-board__form"><div class="hub-board__form-grid"><label>콘텐츠 유형<select name="content_key" required>${Object.entries(BOARD_CONTENTS).map(([key,value])=>`<option value="${key}">${value}</option>`).join('')}</select></label><label>문의 유형<select name="category" required>${Object.entries(BOARD_CATEGORIES).map(([key,value])=>`<option value="${key}">${value}</option>`).join('')}</select></label></div><label>제목<input name="title" required minlength="2" maxlength="120" placeholder="문의 내용을 짧게 요약해 주세요"></label><label>내용<textarea name="body" required minlength="2" maxlength="4000" rows="7" placeholder="상황과 확인이 필요한 부분을 자세히 적어주세요."></textarea></label>${attach(state)}<p class="hub-board__privacy">🔒 글과 사진은 작성자 본인과 LAC HUB 운영자만 확인할 수 있습니다.</p>${formActions()}</form></section>`;
 } else if(mode==='detail'){
  const ticket=board.ticket;
  const mayDelete=Boolean(ticket&&(isAdmin||String(ticket.author_id)===String(state.session?.user?.id||'')));
  contents=!ticket?'<div class="hub-board__empty">게시글을 불러오는 중입니다.</div>':`<article class="hub-board__sheet"><div class="hub-board__sheet-top"><button type="button" data-action="hub-board-cancel">← 목록으로</button><div class="hub-board__ticket-actions">${isAdmin?`<label>처리 상태 <select data-hub-board-status data-ticket-id="${e(ticket.id)}">${Object.entries(BOARD_STATUSES).map(([key,value])=>`<option value="${key}" ${ticket.status===key?'selected':''}>${value}</option>`).join('')}</select></label>`:`<span>${e(label(BOARD_STATUSES,ticket.status))}</span>`}${mayDelete?`<button type="button" class="hub-board__delete" data-action="hub-board-delete" data-ticket-id="${e(ticket.id)}">글 삭제</button>`:''}</div></div><div class="hub-board__detail-head"><span class="hub-board__pill">${e(label(BOARD_CONTENTS,ticket.content_key))}</span><span class="hub-board__pill">${e(label(BOARD_CATEGORIES,ticket.category))}</span><small>${date(ticket.created_at)}</small><h2>${e(ticket.title)}</h2><p>${e(ticket.body)}</p><div class="hub-board__attachments">${fileCards(ticket.attachments)}</div></div><div class="hub-board__messages"><h3>답변 · 추가 문의 <small>${ticket.messages?.length||0}</small></h3>${(ticket.messages||[]).map(item=>`<div class="hub-board__message ${item.is_staff?'is-staff':''}"><div><b>${e(item.is_staff?'LAC HUB 운영자':'작성자')}</b><small>${date(item.created_at)}</small></div><p>${e(item.body)}</p><div class="hub-board__attachments">${fileCards(ticket.attachments,item.id)}</div></div>`).join('')||'<p class="hub-board__empty">답변을 기다리고 있습니다.</p>'}</div><form class="hub-board__form hub-board__reply" data-form="hub-board-reply"><label>답변 작성<textarea required name="body" rows="4" maxlength="4000" placeholder="추가 설명이나 답변을 작성해 주세요."></textarea></label>${attach(state)}${formActions('답변 등록')}</form></article>`;
 } else if(mode==='notice'){
  const notice=notices.find(item=>item.id===board.noticeId);
  const adminActions=notice&&isAdmin?`<div class="hub-board__ticket-actions"><button type="button" class="hub-board__ghost" data-action="hub-board-notice-edit" data-notice-id="${e(notice.id)}">${icon('pencil',14)} 수정</button><button type="button" class="hub-board__delete" data-action="hub-board-notice-delete" data-notice-id="${e(notice.id)}">삭제</button></div>`:'';
  contents=`<article class="hub-board__sheet"><div class="hub-board__sheet-top"><button type="button" data-action="hub-board-cancel">← 공지 목록</button>${adminActions}</div>${notice?`<div class="hub-board__detail-head"><span class="hub-board__pill hub-board__pill--notice">공지</span><small>${date(notice.published_at)}</small><h2>${e(notice.title)}</h2><div class="hub-board__notice-content">${noticeBodyHtml(notice.body)}</div></div>`:'<p class="hub-board__empty">공지를 찾지 못했습니다.</p>'}</article>`;
 } else if(mode==='notice-compose'&&isAdmin){
  contents=`<section class="hub-board__sheet"><div class="hub-board__sheet-top">새 공지 작성<button type="button" data-action="hub-board-cancel">×</button></div><form class="hub-board__form" data-form="hub-board-notice"><label>공지 제목<input name="title" required minlength="2" maxlength="120"></label><label>공지 내용<textarea name="body" rows="10" required minlength="2" maxlength="4000" data-hub-notice-body placeholder="내용을 작성하고, 사진을 넣을 위치에서 Ctrl+V로 붙여넣어 주세요."></textarea></label>${noticeAttach(state)}${formActions('공지 등록')}</form></section>`;
 } else if(mode==='notice-edit'&&isAdmin){
  const notice=notices.find(item=>item.id===board.noticeId);
  contents=notice?`<section class="hub-board__sheet"><div class="hub-board__sheet-top"><span>공지 수정</span><button type="button" data-action="hub-board-cancel">×</button></div><form class="hub-board__form" data-form="hub-board-notice-edit"><label>공지 제목<input name="title" required minlength="2" maxlength="120" value="${e(notice.title)}"></label><label>공지 내용<textarea name="body" rows="10" required minlength="2" maxlength="4000" data-hub-notice-body>${e(board.noticeEditorBody??notice.body)}</textarea></label>${noticeAttach(state)}${formActions('변경사항 저장')}</form></section>`:'<p class="hub-board__empty">수정할 공지를 찾지 못했습니다.</p>';
 } else { contents=tab==='notices'?noticeList+noticeInfo:supportProgress+tickets; }
 const noticeMode=['notice-compose','notice-edit','notice'].includes(mode);
 const writeSide=`<aside class="hub-board__side"><div class="hub-board__side-card hub-board__side-card--guide"><span class="hub-board__section-kicker">LAC HUB SUPPORT</span><h2>${noticeMode?'공지사항':'문의 안내'}</h2><p>${noticeMode?'플랫폼 운영자의 공지사항을 확인하는 공간입니다.':'콘텐츠 유형과 문의 유형을 정확히 선택해 주세요.'}</p><div class="hub-board__side-art" aria-hidden="true"></div><p>${noticeMode?'공지 본문에는 필요한 위치에 이미지를 붙여넣어 함께 안내할 수 있습니다.':'문의 내용이 복잡하다면 화면 사진을 첨부해 주세요.'}</p><div class="hub-board__private-note">${noticeMode?'▣ 공지 내용과 삽입 이미지는 모든 LAC HUB 이용자에게 공개됩니다.':'▣ 문의와 첨부 사진은 작성자 및 운영자에게만 공개됩니다.'}</div></div></aside>`;
 const pageSide=mode==='list'?(tab==='notices'?noticesSide:supportSide):writeSide;
 const legacy=state.companies?.length?`<aside class="hub-board__legacy"><span>이전 회사 문의 기록</span><button type="button" data-page="questions">기존 질문 내역 →</button><button type="button" data-page="suggestions">기존 건의 내역 →</button></aside>`:'';
 return `<div class="hub-board"><main class="hub-board__container">${top}${heading}${message}<div class="hub-board__navrow">${mode==='list'?tabs:`<div class="hub-board__subnav"><span class="hub-board__section-kicker">${mode==='compose'?'WRITE A REQUEST':mode==='detail'?'SUPPORT DETAIL':'NOTICE'}</span><strong>${mode==='compose'?'문의 · 건의 작성':mode==='detail'?'문의 상세':mode==='notice-compose'?'새 공지 작성':mode==='notice-edit'?'공지 수정':'공지 상세'}</strong></div>`}${mode==='list'&&tab==='support'?`<button type="button" class="hub-board__primary hub-board__write-top" data-action="hub-board-compose">${icon('pencil',15)} 문의 · 건의 작성</button>`:''}</div><div class="hub-board__layout">${pageSide}<div class="hub-board__main">${contents}${mode==='list'&&tab==='support'?recentReplies:''}</div></div>${legacy}<footer class="hub-board__footer">LAC HUB · 공지는 전체 공개 · 문의와 첨부 사진은 작성자 및 운영자에게만 공개</footer></main></div>`;
}
