import { readFileSync, existsSync } from 'node:fs';
import assert from 'node:assert/strict';
const f=(p)=>readFileSync(new URL(`../${p}`, import.meta.url),'utf8');
const app=f('build/src/App.jsx'), h=f('hub/src/ui/hubHome.js'), bs=f('build/src/lib/supabase.js'), hs=f('hub/src/lib/supabase.js');
const routeKeys=['/build/','/build/builds','/build/notices','/build/presets','/build/modbooks','/build/weapons','/build/reports','/build/admin'];
for(const route of routeKeys)assert.ok(app.includes(`"${route}"`),`route missing ${route}`);
assert.ok(f('build/vite.config.js').includes('base: "/build/"'));
assert.ok(app.includes('const redirectTo = `${window.location.origin}/build/`;'));
assert.ok(!app.includes('VITE_SITE_URL || window.location.origin'),'unified BUILD must not return to old independent origin');
assert.ok(h.includes("const BUILD_PUBLIC_URL = '/build/';"));
assert.ok(!h.includes('https://axe-hub-peach.vercel.app/'),'unified entry must remain same origin');
assert.ok(h.includes('href.startsWith("/build/")'));
assert.ok(bs.includes('createClient(url, key') && hs.includes('createClient(url, publishableKey'));
assert.ok(bs.includes('persistSession: true') && hs.includes('persistSession: true'));
assert.ok(!app.includes('src="/assets/'),'BUILD assets must be scoped');
assert.ok(!app.includes('image: "/assets/'),'clothing assets must be scoped');
assert.ok(!f('build/src/styles.css').includes("url('/assets/"),'CSS background assets must be scoped');
const routes=JSON.parse(f('vercel.json')).rewrites;for(const route of routeKeys.filter(x=>x!=='/build/'))assert.ok(routes.some(r=>r.source===route));
const spaFallbackSources=['/game','/game/','/game/:path*','/company','/company/','/company/:path*','/admin','/admin/','/admin/:path*','/notices','/notices/','/support','/support/'];
for(const route of spaFallbackSources)assert.ok(routes.some(r=>r.source===route&&r.destination==='/index.html'),`SPA fallback missing ${route}`);
for(const route of ['/company/access','/company/access/'])assert.ok(routes.some(r=>r.source===route&&r.destination==='/index.html'),`Company access direct refresh fallback missing ${route}`);
for(const p of ['hub/api/discord/callback.js','hub/src/lib/productApi.js','build/public/assets/equipment/top-team.webp','build/public/assets/equipment/bottom-team.webp','build/public/assets/equipment/outer-team.webp','build/public/assets/equipment/shoes-team.webp'])assert.ok(existsSync(new URL(`../${p}`,import.meta.url)),`source missing ${p}`);
console.log('PASS: same-origin integration routes, asset isolation, OAuth return, existing functions and clothing preserved.');
console.log('NOTE: static checks do not verify live authentication, authorization, build, or database access.');
